name: Build as Artifacts

on:
  - push
  - pull_request

permissions: read-all

env:
  OCAMLRUNPARAM: "b"

jobs:
  build-and-test:
    permissions:
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 5
        include:
          # https://gitlab.com/camlspotter/camlimages/-/issues/6
          - os: ubuntu-latest
            ocaml-compiler: 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      # Ubuntuの場合のみ実行
      - name: Install libjpeg on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - name: Prepare distribution directory
        if: runner.os == 'Linux'
        run: |
          mkdir -p dist/ocaml_photo_modifier
          cp _build/default/bin/main.exe dist/ocaml_photo_modifier/
          cp scripts/run.sh dist/ocaml_photo_modifier/
          cp scripts/run.bat dist/ocaml_photo_modifier/

      - name: Create zip archive
        if: runner.os == 'Linux'
        run: |
          cd dist
          zip -r ocaml_photo_modifier.zip ocaml_photo_modifier

      - name: Generate artifact attestation
        if: runner.os == 'Linux'
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/ocaml_photo_modifier.zip

      - name: Upload the build artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ocaml_photo_modifier-${{ matrix.ocaml-compiler }}.zip
          path: dist/ocaml_photo_modifier.zip

      - name: Run Example
        run: cd sample && echo "hoge" | ../_build/default/bin/main.exe
